### ISSUE TITLE
如何集成到现有原生工程？

### ISSUE THREAD

**Issue by spysoos** [wuba/magpie#10]
请问如何集成到现有原生工程？

**Comment by avenwu** [comment]
可以看README里面的介绍，先创建module，然后关联到app工程

**Comment by spysoos** [comment]
@avenwu 创建moudle是指通过create创建模板工程，然后再把原工程拷贝到.android/.ios 目录下，再通过magpie_sdk关联，是这个意思吗？

**Comment by avenwu** [comment]
不完全，也是通过脚手架创建.
```
mgpcli create -n flutter_module
```

**Comment by spysoos** [comment]
@avenwu 那creater完成后 是在那一步进行对现有工程的关联呢？ 这个项目的wiki会完善吗？

**Comment by avenwu** [comment]
创建完模板后集成到app这块，可以根据文档中的超链提示。因为篇幅较多，在另一个仓库中：
> 与Workflow配套，用于接入App，Flutter的SDK。https://github.com/wuba/magpie_sdk
