### ISSUE TITLE
打包出错！

### ISSUE THREAD

**Issue by spysoos** [wuba/magpie#19]
#13 使用新版magpie后仍有些问题

**Comment by avenwu** [comment]
感谢反馈，继续跟进

**Comment by spysoos** [comment]
问个题外话：如果想Android/Ios 统一使用由flutter 实现的网络基础库，原生在不打开flutter界面的基础上能成功使用这个基础库吗？

**Comment by spysoos** [comment]
https://github.com/wuba/magpie/issues/13#issuecomment-641856744

**Comment by spysoos** [comment]
这个问题可以通过开启 androidx 来解决。但是打包到最后出现了新的错误，不知道构建最后一步要打开什么可执行文件。
![微信截图_20200611112819](https://user-images.githubusercontent.com/982866/84341898-d13cdf80-abd6-11ea-9014-739917dcf52f.png)

**Comment by avenwu** [comment]
0.1.4-hotfix2修复了截图问题
