### ISSUE TITLE
换了台电脑生成脚手架出错

### ISSUE THREAD

**Issue by spysoos** [wuba/magpie#21]
![TIM截图20200611005853](https://user-images.githubusercontent.com/982866/84296560-c191ac80-ab7e-11ea-819f-869be7ac8dc6.png)

本地地址判断是写死的？

**Comment by avenwu** [comment]
换了台电脑是有正常配置环境的？

**Comment by spysoos** [comment]
嗯 照着文档来的，后面用mklink 来解决了。不知道你们是怎么判断本地版本地址的。算不是问题的问题吧
