### ISSUE TITLE
不清楚Mapie workflow 提供的开发编译里的Attach、reload、restart如何使用！

### ISSUE THREAD

**Issue by Alexmego** [wuba/magpie#25]
1. 创建好flutter_sample 之后，调用mgpcli start 在浏览器打开了一个tab【magpie workflow】，第一步连接设备，第二步开发编译，选择好目录和启动入口文件后。下面该如何操作？（点击 attach 说连接设备超时）

2. 第二步既然是开发编译，左下角的【使用说明】里却是提示如何在ide里debug。令人费解，workflow开发编译的这项功能是干嘛的，还有提供的attach ，reload，restart，这些操作都可以在ide 里完成。

3. 我可以把mapie workflow 理解为简化创建工程模板+发布aar两个流程吗？ 至于编译和调试，全部在ide上完成。

-----
以上问题，希望开发者能答疑，祝工作顺利！

**Comment by avenwu** [comment]
针对你的疑问，供参考
1. 超时意味着没有成功与手机上的flutter app建立关联，原因很多比如压根没有flutter app
2. 开发编译不是替代IDE，主要作用是为发布准备。当然你可以选择使用，也可以使用IDE完成
3. 现有功能情况下这是使用较多的功能
